export const themes = [
    { name: 'Indigo', hero: 'bg-gradient-to-b from-indigo-600 to-indigo-800', heroText: 'text-indigo-200', accent: 'text-indigo-500', skillIconBg: 'bg-indigo-100 text-indigo-600', footer: 'bg-[#1C1C1C]', footerCta: 'bg-gradient-to-br from-purple-700 to-indigo-700', button: 'bg-white text-indigo-700 hover:bg-gray-200', animation: { type: 'skew', delay: 10 } },
    { name: 'Sky', hero: 'bg-gradient-to-b from-sky-500 to-cyan-500', heroText: 'text-sky-100', accent: 'text-sky-500', skillIconBg: 'bg-sky-100 text-sky-600', footer: 'bg-slate-800', footerCta: 'bg-gradient-to-br from-sky-600 to-cyan-600', button: 'bg-white text-sky-700 hover:bg-gray-200', animation: { type: 'fade-up', delay: 20 } },
    { name: 'Emerald', hero: 'bg-gradient-to-b from-emerald-500 to-green-600', heroText: 'text-emerald-100', accent: 'text-emerald-500', skillIconBg: 'bg-emerald-100 text-emerald-600', footer: 'bg-gray-800', footerCta: 'bg-gradient-to-br from-emerald-600 to-green-700', button: 'bg-white text-emerald-700 hover:bg-gray-200', animation: { type: 'scale-up', delay: 25 } },
    { name: 'Rose', hero: 'bg-gradient-to-b from-rose-500 to-pink-600', heroText: 'text-rose-100', accent: 'text-rose-500', skillIconBg: 'bg-rose-100 text-rose-600', footer: 'bg-slate-900', footerCta: 'bg-gradient-to-br from-rose-600 to-pink-700', button: 'bg-white text-rose-700 hover:bg-gray-200', animation: { type: 'rotate-in', delay: 20 } },
    { name: 'Amber', hero: 'bg-gradient-to-b from-amber-500 to-orange-600', heroText: 'text-amber-100', accent: 'text-amber-500', skillIconBg: 'bg-amber-100 text-amber-600', footer: 'bg-stone-800', footerCta: 'bg-gradient-to-br from-amber-600 to-orange-700', button: 'bg-white text-amber-700 hover:bg-gray-200', animation: { type: 'skew', delay: 10 } },
    { name: 'Slate', hero: 'bg-gradient-to-b from-slate-600 to-gray-800', heroText: 'text-slate-200', accent: 'text-slate-500', skillIconBg: 'bg-slate-200 text-slate-600', footer: 'bg-black', footerCta: 'bg-gradient-to-br from-slate-700 to-gray-900', button: 'bg-white text-slate-700 hover:bg-gray-200', animation: { type: 'fade-up', delay: 20 } },
    { name: 'Fuchsia', hero: 'bg-gradient-to-b from-fuchsia-600 to-violet-700', heroText: 'text-fuchsia-200', accent: 'text-fuchsia-500', skillIconBg: 'bg-fuchsia-100 text-fuchsia-600', footer: 'bg-gray-900', footerCta: 'bg-gradient-to-br from-fuchsia-700 to-violet-800', button: 'bg-white text-fuchsia-700 hover:bg-gray-200', animation: { type: 'rotate-in', delay: 20 } },
    { name: 'Teal', hero: 'bg-gradient-to-b from-teal-500 to-cyan-600', heroText: 'text-teal-100', accent: 'text-teal-500', skillIconBg: 'bg-teal-100 text-teal-600', footer: 'bg-slate-800', footerCta: 'bg-gradient-to-br from-teal-600 to-cyan-700', button: 'bg-white text-teal-700 hover:bg-gray-200', animation: { type: 'scale-up', delay: 25 } },
    { name: 'Red', hero: 'bg-gradient-to-b from-red-600 to-rose-700', heroText: 'text-red-200', accent: 'text-red-500', skillIconBg: 'bg-red-100 text-red-600', footer: 'bg-neutral-900', footerCta: 'bg-gradient-to-br from-red-700 to-rose-800', button: 'bg-white text-red-700 hover:bg-gray-200', animation: { type: 'skew', delay: 10 } },
    { name: 'Lime', hero: 'bg-gradient-to-b from-lime-500 to-green-500', heroText: 'text-lime-100', accent: 'text-lime-500', skillIconBg: 'bg-lime-100 text-lime-600', footer: 'bg-gray-800', footerCta: 'bg-gradient-to-br from-lime-600 to-green-700', button: 'bg-white text-lime-700 hover:bg-gray-200', animation: { type: 'fade-up', delay: 20 } }
];